server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3356/noshow_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: love1004

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/static/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
